### ISSUE TITLE
how to receive different events from player?

### ISSUE THREAD

**Issue by sirvon** [crashoverride777/SwiftyMusic#1]
I would like to catch notifications of different events like music stopped, etc etc?

Is there a way to do that with this library using delegation instead of NSNotificationCenter?

Thanks!

**Comment by crashoverride777** [comment]
Hey, 

Thanks for using my helper. Yes delegation will probably be the best way.

Create a protocol above the Swifty Music class with your event callbacks

       protocol MusicDelegate: class {
          func didPause()
          func didResume() 
          ....
     }

Than inside the Swifty Music class create the delegate property

        weak var delegate: MusicDelegate?

and go to the methods like mute/ resume and call the delegates at the end e.g

       delegate?.didPause()

Than you can go to your relevant SKScene/VC where you want the events/callback and set the delegate

      SwiftyMusic.shared.delegate = self

and implement the methods

      extension SOMECLASS: MusicDelegate {
           func didPause() {
                // do something
          }
           ....
     }
    
Hope this helps
